var app = document.getElementById('app');

var typewriter = new Typewriter(app, {
    loop: true
});

typewriter.typeString(' Developer')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Mentor')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Motivator')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Content Writer' )
    .pauseFor(800)
    .deleteAll()
    .typeString(' Tech Blogger')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Innovator')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Creator')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Speaker')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Teacher')
    .pauseFor(800)
    .deleteAll()
    .typeString(' Fullstack Web Developer')
    .pauseFor(800)
    .deleteAll()
    .typeString('Computer Vision Enthusiast')
    .pauseFor(800)
    .deleteAll()
    .typeString('Machine Learning Enthusiast')
    .pauseFor(800)
    .deleteAll()
    .typeString('Cadet Who Develops')
    .pauseFor(00)
    .deleteChars(8)
    .typeString('Codes')
    .pauseFor(3200)
    .start();